---

  - name: copy init config
    copy: src=init/oracle-init.conf dest=/tmp/oracle-xe.conf owner=root group=root mode=0755

  - name: stop oracle-xe
    service: name=oracle-xe state=stopped

  - name: Configure instance
    copy: src={{item}} dest=/u01/app/oracle/product/11.2.0/xe/config/scripts/ owner=oracle group=dba mode=0755
    with_fileglob:
      - config/*.ora

  - name: remove previous configuration
    file: path=/etc/sysconfig/oracle-xe state=absent

  - name: configure oracle-xe
    shell: /etc/init.d/oracle-xe configure < /tmp/oracle-xe.conf >> /tmp/oracle-xe.log
