---

  - name: Deploy war
    copy:
      src: "{{item}}"
      dest: /usr/share/tomcat/webapps/example.war
      mode: 0644
    with_fileglob:
      - "war/*.war"

  - name: Start & Enable tomcat
    systemd:
      name: tomcat
      daemon-reload: true
      state: started
      enabled: true

  - name: copy monitoring shell
    copy:
      src: "{{item}}"
      dest: /work/shell
      mode: 0744
    with_fileglob:
      - "shell/*.sh"